pipeline {
    agent any
    environment{
        DOCKERHUB_CREDS = credentials('DockerHub')
    }
    stages {
        stage('Clone Repo') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/ShubhamArora073/devopscourse.git']])
                sh 'ls *'
            }
        }
        stage('Build Image') {
            steps {
                //sh 'docker build -t Shubhamarora073/jenkinstest ./pushdockerimage/' (this will use the tag latest)
		sh 'docker build -t Shubhamarora073/jenkinstest:$BUILD_NUMBER ./pushdockerimage/'
            }
        }
        stage('Docker Login') {
            steps {
                //sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW' (this will leave the password visible)
                sh 'echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin'                
                }
            }
        stage('Docker Push') {
            steps {
		//sh 'docker push Shubhamarora073/jenkinstest' (this will use the tag latest)    
                sh 'docker push Shubhamarora073/jenkinstest:$BUILD_NUMBER'
                }
            }
        }
    post {
		always {
			sh 'docker logout'
		}
	 }
    }

